version: '3.8'

services:
  # Development backend with hot reload
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./app:/app/app
      - ./images:/app/images
      - ./models:/app/models
      - ./logs:/app/logs
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped

  # Development frontend with hot reload
  frontend-dev:
    image: node:18-alpine
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend-dev
    restart: unless-stopped

networks:
  default:
    name: planit-dev-network
